# Generated by Django 4.1.3 on 2022-11-29 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('palavras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palavra',
            name='user',
        ),
        migrations.CreateModel(
            name='PalavraUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('palavra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palavras.palavra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
