# Generated by Django 4.1.3 on 2022-12-03 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('palavras', '0002_remove_palavrausuario_data_palavrausuario_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palavrausuario',
            name='password',
        ),
        migrations.RemoveField(
            model_name='palavrausuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='palavrausuario',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='palavrausuario',
            name='palavra',
            field=models.CharField(max_length=5),
        ),
    ]
